python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=3.7
  - conda activate test-environment
  - conda install numpy=1.21.6 pandas=1.2.0 matplotlib=3.5.2 sphinx=5.0.2 ipython=7.33.0 xlrd=1.2.0 tabulate=0.8.10 openpyxl=3.0.9 scipy=1.7.3 scikit-learn=1.0.2 --channel conda-forge
  - conda install pydata-sphinx-theme=0.9.0 --channel conda-forge

script:
  - make clean
  - make html